[cohere]
api_key = "g9e49CMQGTCgaEAYVYt64Rt6LMEL7WZ3usCBQ2fW"

[zoom]
account_id = "HaOzz0dfSreksBe39Odrzw"
client_id = "b0sTf5N9SNuR5fWOPXrVHg"
client_secret = "BTj96DjPJ1tIM8FuC4i549qCVAlTu5ik"
user_id = "me"
redirect_uri = "http://localhost:8501/oauth/callback"


